### PR TITLE
fix tokenized sentence problem

### PR DESCRIPTION
**Pull request by judaschrist**
If BertClient.encode is to be called with is_tokenized parameter set to True, There will be an exception because the client didn't find the mark_unk_tokens function. I added it from the original ber_base to fix this problem. Also, I am not sure the point of "vocab.get(item, 100)", because unknown tokens have already been taken care of. And I haven't encountered any problem changing it back to vocab[item], do let me know if you have any problem with the first commit.

### CODE REVIEW

**Comment by macanv** [comment]
thanks for your request.
vocab.get(item, 100) means  if the item not in vocab.txt, using '[UNK]' replace, so the funcion of mark_unk_tokens is not required.
I think the importance is how to fix OOV problams while we training special in predict task.

**Comment by judaschrist** [comment]
vocab.get(item, 100) does not fix the problem, try calling BertClient.encode with is_tokenized parameter set to True, the code will attempt to call mark_unk_tokens function and will raise an exception.
Actually the with mark_unk_tokens function the code will mark any OOV with [unk], so there's no need to worry about oov

**Comment by macanv** [comment]
it is client input params rule problems, I think all logical op should do in server not in userinterface.

**Comment by judaschrist** [comment]
If you don't want to fix it, at least remove "is_tokenized" parameter from BertClient.encode function because it's useless in your implementation

**Pull request closed without merging**
